@PATH C:\PROGRA~1\WIN98RK;%PATH%
mode con codepage prepare=((850) C:\WINDOWS\COMMAND\ega.cpi)
mode con codepage select=850
keyb uk,,C:\WINDOWS\COMMAND\keyboard.sys
subst z: d:\
alias /r d:\stuff\4dos\aliases
path c:\progra~1\win98rk;c:\windows;c:\windows\command;d:\stuff\4dos;c:\brief;c:\bat
set bpath=;c:\brief\macros
set bhelp=c:\brief\help
set bfile=c:\brief\state.rst
set bflags=-i120kr -mJM -mrestore
