//ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ
// Global Header File For <LEGO Rock Raiders>
//
// Started:	10-07-98
// Coding:	Glenn Benson
//‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹

#ifndef	__GLOBALS_H

//ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ
// Include All Library Stuff
//‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹
#include "libgods.h"

#define	END_LIST	0xdeadFACE


//ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ
// Include All Game Stuff
//‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹



#include	"map3d.h"
#include	"loader.h"
#include	"sfx.h"
#include	"lego.h"
#include	"steve.h"
#include	"control.h"
#include	"trigger.h"
#include   "objects.h"
#include	"console.h"
#include	"surface.h"
#include	"camera.h"
#include	"libpad.h"
#include	"cd.h"
#include	"boulder.h"
#include	"craft.h"
#include	"player.h"
#include	"creature.h"
#include   "spider.h"
#include   "snake.h"
#include   "scorpion.h"
#include   "rmonster.h"
#include   "rwhale.h"
#include	"editor.h"

#define	__GLOBALS_H
#endif






