/// Microsoft Windows API
/// <https://docs.microsoft.com/en-us/cpp/c-runtime-library/c-run-time-library-reference>
///
/// this file contains a list of all known WINAPI functions used by LegoRR...
/// this'll take awhile to get to...