
#include "NERPs.h"
#include "NERPs_Functions.h"


/// NOTE: A few functions are reused in multiple places
///       NERPFunc__False             : used for all functions returning 0 (i.e. for "Null") and other non-implemented functions
///       NERPFunc__SetLevelCompleted : used for SetGameCompleted as well


// last item is "**End Of List**"
// <LegoRR.exe @004a6948 -> 004a7710>
NERPSFunction g_NERPS_FUNCTIONS[294] = {
	/*0  */ { "Stop",                            NERPFunc__False,                           NERPS_ARGS_0_NORETURN }, // (hardcoded functionality)
	/*1  */ { "True",                            NERPFunc__True,                            NERPS_ARGS_0 },
	/*2  */ { "False",                           NERPFunc__False,                           NERPS_ARGS_0 },
	/*3  */ { "Null",                            NERPFunc__False,                           NERPS_ARGS_0 },
	/*4  */ { "GetRandom",                       NERPFunc__GetRandom,                       NERPS_ARGS_0 },
	/*5  */ { "GetRandom10",                     NERPFunc__GetRandom10,                     NERPS_ARGS_0 },
	/*6  */ { "GetRandom100",                    NERPFunc__GetRandom100,                    NERPS_ARGS_0 },
	/*7  */ { "GetRandomTrueFalse",              NERPFunc__GetRandomTrueFalse,              NERPS_ARGS_0 },
	/*8  */ { "SetLevelCompleted",               NERPFunc__SetLevelCompleted,               NERPS_ARGS_0_NORETURN },
	/*9  */ { "SetLevelFail",                    NERPFunc__SetLevelFail,                    NERPS_ARGS_0_NORETURN },
	/*10 */ { "SetGameCompleted",                NERPFunc__SetLevelCompleted,               NERPS_ARGS_0_NORETURN },
	/*11 */ { "SetGameFail",                     NERPFunc__SetGameFail,                     NERPS_ARGS_0_NORETURN },
	/*12 */ { "GetCrystalsPickedUp",             NERPFunc__GetCrystalsPickedUp,             NERPS_ARGS_0 },
	/*13 */ { "GetCrystalsCurrentlyStored",      NERPFunc__GetCrystalsCurrentlyStored,      NERPS_ARGS_0 },
	/*14 */ { "GetCrystalsUsed",                 NERPFunc__False,                           NERPS_ARGS_0 }, // (not implemented)
	/*15 */ { "GetCrystalsStolen",               NERPFunc__False,                           NERPS_ARGS_0 }, // (not implemented)
	/*16 */ { "SetMessage",                      NERPFunc__SetMessage,                      NERPS_ARGS_2_NORETURN },
	/*17 */ { "GetR0",                           NERPFunc__GetR0,                           NERPS_ARGS_0 },
	/*18 */ { "GetR1",                           NERPFunc__GetR1,                           NERPS_ARGS_0 },
	/*19 */ { "GetR2",                           NERPFunc__GetR2,                           NERPS_ARGS_0 },
	/*20 */ { "GetR3",                           NERPFunc__GetR3,                           NERPS_ARGS_0 },
	/*21 */ { "GetR4",                           NERPFunc__GetR4,                           NERPS_ARGS_0 },
	/*22 */ { "GetR5",                           NERPFunc__GetR5,                           NERPS_ARGS_0 },
	/*23 */ { "GetR6",                           NERPFunc__GetR6,                           NERPS_ARGS_0 },
	/*24 */ { "GetR7",                           NERPFunc__GetR7,                           NERPS_ARGS_0 },
	/*25 */ { "SetR0",                           NERPFunc__SetR0,                           NERPS_ARGS_1_NORETURN },
	/*26 */ { "SetR1",                           NERPFunc__SetR1,                           NERPS_ARGS_1_NORETURN },
	/*27 */ { "SetR2",                           NERPFunc__SetR2,                           NERPS_ARGS_1_NORETURN },
	/*28 */ { "SetR3",                           NERPFunc__SetR3,                           NERPS_ARGS_1_NORETURN },
	/*29 */ { "SetR4",                           NERPFunc__SetR4,                           NERPS_ARGS_1_NORETURN },
	/*30 */ { "SetR5",                           NERPFunc__SetR5,                           NERPS_ARGS_1_NORETURN },
	/*31 */ { "SetR6",                           NERPFunc__SetR6,                           NERPS_ARGS_1_NORETURN },
	/*32 */ { "SetR7",                           NERPFunc__SetR7,                           NERPS_ARGS_1_NORETURN },
	/*33 */ { "AddR0",                           NERPFunc__AddR0,                           NERPS_ARGS_1_NORETURN },
	/*34 */ { "AddR1",                           NERPFunc__AddR1,                           NERPS_ARGS_1_NORETURN },
	/*35 */ { "AddR2",                           NERPFunc__AddR2,                           NERPS_ARGS_1_NORETURN },
	/*36 */ { "AddR3",                           NERPFunc__AddR3,                           NERPS_ARGS_1_NORETURN },
	/*37 */ { "AddR4",                           NERPFunc__AddR4,                           NERPS_ARGS_1_NORETURN },
	/*38 */ { "AddR5",                           NERPFunc__AddR5,                           NERPS_ARGS_1_NORETURN },
	/*39 */ { "AddR6",                           NERPFunc__AddR6,                           NERPS_ARGS_1_NORETURN },
	/*40 */ { "AddR7",                           NERPFunc__AddR7,                           NERPS_ARGS_1_NORETURN },
	/*41 */ { "SubR0",                           NERPFunc__SubR0,                           NERPS_ARGS_1_NORETURN },
	/*42 */ { "SubR1",                           NERPFunc__SubR1,                           NERPS_ARGS_1_NORETURN },
	/*43 */ { "SubR2",                           NERPFunc__SubR2,                           NERPS_ARGS_1_NORETURN },
	/*44 */ { "SubR3",                           NERPFunc__SubR3,                           NERPS_ARGS_1_NORETURN },
	/*45 */ { "SubR4",                           NERPFunc__SubR4,                           NERPS_ARGS_1_NORETURN },
	/*46 */ { "SubR5",                           NERPFunc__SubR5,                           NERPS_ARGS_1_NORETURN },
	/*47 */ { "SubR6",                           NERPFunc__SubR6,                           NERPS_ARGS_1_NORETURN },
	/*48 */ { "SubR7",                           NERPFunc__SubR7,                           NERPS_ARGS_1_NORETURN },
	/*49 */ { "SetMessagePermit",                NERPFunc__SetMessagePermit,                NERPS_ARGS_1_NORETURN },
	/*50 */ { "GetObjectiveShowing",             NERPFunc__GetObjectiveShowing,             NERPS_ARGS_0 },
	/*51 */ { "GetTeleportIconClicked",          NERPFunc__GetTeleportIconClicked,          NERPS_ARGS_0 },
	/*52 */ { "GetMiniFiguresOnLevel",           NERPFunc__GetMiniFiguresOnLevel,           NERPS_ARGS_0 },
	/*53 */ { "GetBuildIconClicked",             NERPFunc__GetBuildIconClicked,             NERPS_ARGS_0 },
	/*54 */ { "SetBuildIconClicked",             NERPFunc__SetBuildIconClicked,             NERPS_ARGS_1_NORETURN },
	/*55 */ { "SetTeleportIconClicked",          NERPFunc__SetTeleportIconClicked,          NERPS_ARGS_1_NORETURN },
	/*56 */ { "SetToolStoreIconClicked",         NERPFunc__SetToolStoreIconClicked,         NERPS_ARGS_1_NORETURN },
	/*57 */ { "GetToolStoreIconClicked",         NERPFunc__GetToolStoreIconClicked,         NERPS_ARGS_0 },
	/*58 */ { "FlashToolStoreIcon",              NERPFunc__FlashToolStoreIcon,              NERPS_ARGS_1_NORETURN },
	/*59 */ { "FlashBuildIcon",                  NERPFunc__FlashBuildIcon,                  NERPS_ARGS_1_NORETURN },
	/*60 */ { "FlashTeleportIcon",               NERPFunc__FlashTeleportIcon,               NERPS_ARGS_1_NORETURN },
	/*61 */ { "SetGoBackIconClicked",            NERPFunc__SetGoBackIconClicked,            NERPS_ARGS_1_NORETURN },
	/*62 */ { "GetGoBackIconClicked",            NERPFunc__GetGoBackIconClicked,            NERPS_ARGS_0 },
	/*63 */ { "FlashGoBackIcon",                 NERPFunc__FlashGoBackIcon,                 NERPS_ARGS_1_NORETURN },
	/*64 */ { "SetDigIconClicked",               NERPFunc__SetDigIconClicked,               NERPS_ARGS_1_NORETURN },
	/*65 */ { "GetDigIconClicked",               NERPFunc__GetDigIconClicked,               NERPS_ARGS_0 },
	/*66 */ { "FlashDigIcon",                    NERPFunc__FlashDigIcon,                    NERPS_ARGS_1_NORETURN },
	/*67 */ { "GetTimer0",                       NERPFunc__GetTimer0,                       NERPS_ARGS_0 },
	/*68 */ { "GetTimer1",                       NERPFunc__GetTimer1,                       NERPS_ARGS_0 },
	/*69 */ { "GetTimer2",                       NERPFunc__GetTimer2,                       NERPS_ARGS_0 },
	/*70 */ { "GetTimer3",                       NERPFunc__GetTimer3,                       NERPS_ARGS_0 },
	/*71 */ { "SetTimer0",                       NERPFunc__SetTimer0,                       NERPS_ARGS_1_NORETURN },
	/*72 */ { "SetTimer1",                       NERPFunc__SetTimer1,                       NERPS_ARGS_1_NORETURN },
	/*73 */ { "SetTimer2",                       NERPFunc__SetTimer2,                       NERPS_ARGS_1_NORETURN },
	/*74 */ { "SetTimer3",                       NERPFunc__SetTimer3,                       NERPS_ARGS_1_NORETURN },
	/*75 */ { "GetBarracksBuilt",                NERPFunc__GetBarracksBuilt,                NERPS_ARGS_0 },
	/*76 */ { "GetOreRefineriesBuilt",           NERPFunc__GetOreRefineriesBuilt,           NERPS_ARGS_0 },
	/*77 */ { "GetToolStoresBuilt",              NERPFunc__GetToolStoresBuilt,              NERPS_ARGS_0 },
	/*78 */ { "GetStudCount",                    NERPFunc__GetStudCount,                    NERPS_ARGS_0 },
	/*79 */ { "GetTeleportsBuilt",               NERPFunc__GetTeleportsBuilt,               NERPS_ARGS_0 },
	/*80 */ { "GetMiniFigureSelected",           NERPFunc__GetMiniFigureSelected,           NERPS_ARGS_0 },
	/*81 */ { "GetSmallDiggerSelected",          NERPFunc__GetSmallDiggerSelected,          NERPS_ARGS_0 },
	/*82 */ { "GetMiniFigureinSmallDigger",      NERPFunc__GetMiniFigureinSmallDigger,      NERPS_ARGS_0 },
	/*83 */ { "GetTrainFlags",                   NERPFunc__GetTrainFlags,                   NERPS_ARGS_0 },
	/*84 */ { "SetTrainFlags",                   NERPFunc__SetTrainFlags,                   NERPS_ARGS_1_NORETURN },
	/*85 */ { "SetIconPos",                      NERPFunc__SetIconPos,                      NERPS_ARGS_2_NORETURN },
	/*86 */ { "SetIconSpace",                    NERPFunc__SetIconSpace,                    NERPS_ARGS_1_NORETURN },
	/*87 */ { "SetIconWidth",                    NERPFunc__SetIconWidth,                    NERPS_ARGS_1_NORETURN },
	/*88 */ { "SetMessageWait",                  NERPFunc__SetMessageWait,                  NERPS_ARGS_1_NORETURN },
	/*89 */ { "GetMountIconClicked",             NERPFunc__GetMountIconClicked,             NERPS_ARGS_0 },
	/*90 */ { "SetMountIconClicked",             NERPFunc__SetMountIconClicked,             NERPS_ARGS_1_NORETURN },
	/*91 */ { "FlashMountIcon",                  NERPFunc__FlashMountIcon,                  NERPS_ARGS_1_NORETURN },
	/*92 */ { "SetTutorialPointer",              NERPFunc__SetTutorialPointer,              NERPS_ARGS_2_NORETURN },
	/*93 */ { "GetTutorialFlags",                NERPFunc__GetTutorialFlags,                NERPS_ARGS_0 },
	/*94 */ { "SetTutorialFlags",                NERPFunc__SetTutorialFlags,                NERPS_ARGS_1_NORETURN },
	/*95 */ { "SetRockMonster",                  NERPFunc__SetRockMonster,                  NERPS_ARGS_2_NORETURN },
	/*96 */ { "GetOrePickedUp",                  NERPFunc__GetOrePickedUp,                  NERPS_ARGS_0 },
	/*97 */ { "GetOreCurrentlyStored",           NERPFunc__GetOreCurrentlyStored,           NERPS_ARGS_0 },
	/*98 */ { "GetOreUsed",                      NERPFunc__False,                           NERPS_ARGS_0 }, // (not implemented)
	/*99 */ { "GetOreStolen",                    NERPFunc__False,                           NERPS_ARGS_0 }, // (not implemented)
	/*100*/ { "GetCrystalRefineriesBuilt",       NERPFunc__GetCrystalRefineriesBuilt,       NERPS_ARGS_0 },
	/*101*/ { "FlashLayPathIcon",                NERPFunc__FlashLayPathIcon,                NERPS_ARGS_1_NORETURN },
	/*102*/ { "SetLayPathIconClicked",           NERPFunc__SetLayPathIconClicked,           NERPS_ARGS_1_NORETURN },
	/*103*/ { "GetLayPathIconClicked",           NERPFunc__GetLayPathIconClicked,           NERPS_ARGS_0 },
	/*104*/ { "GetTeleportPadIconClicked",       NERPFunc__GetTeleportPadIconClicked,       NERPS_ARGS_0 },
	/*105*/ { "SetTeleportPadIconClicked",       NERPFunc__SetTeleportPadIconClicked,       NERPS_ARGS_1_NORETURN },
	/*106*/ { "FlashTeleportPadIcon",            NERPFunc__FlashTeleportPadIcon,            NERPS_ARGS_1_NORETURN },
	/*107*/ { "GetMessageTimer",                 NERPFunc__GetMessageTimer,                 NERPS_ARGS_0 },
	/*108*/ { "SetMessageTimerValues",           NERPFunc__SetMessageTimerValues,           NERPS_ARGS_3_NORETURN },
	/*109*/ { "GetTutorialBlockClicks",          NERPFunc__GetTutorialBlockClicks,          NERPS_ARGS_1 },
	/*110*/ { "SetTutorialBlockClicks",          NERPFunc__SetTutorialBlockClicks,          NERPS_ARGS_2_NORETURN },
	/*111*/ { "GetTutorialCrystals",             NERPFunc__GetTutorialCrystals,             NERPS_ARGS_1 },
	/*112*/ { "SetTutorialCrystals",             NERPFunc__SetTutorialCrystals,             NERPS_ARGS_2_NORETURN },
	/*113*/ { "GetPathsBuilt",                   NERPFunc__GetPathsBuilt,                   NERPS_ARGS_0 },
	/*114*/ { "GetTutorialBlockIsGround",        NERPFunc__GetTutorialBlockIsGround,        NERPS_ARGS_1 },
	/*115*/ { "SetCameraGotoTutorial",           NERPFunc__SetCameraGotoTutorial,           NERPS_ARGS_1_NORETURN },
	/*116*/ { "FlashDynamiteIcon",               NERPFunc__FlashDynamiteIcon,               NERPS_ARGS_1_NORETURN },
	/*117*/ { "GetDynamiteClicked",              NERPFunc__GetDynamiteClicked,              NERPS_ARGS_0 },
	/*118*/ { "SetDynamiteClicked",              NERPFunc__SetDynamiteClicked,              NERPS_ARGS_1_NORETURN },
	/*119*/ { "AddPoweredCrystals",              NERPFunc__AddPoweredCrystals,              NERPS_ARGS_1_NORETURN },
	/*120*/ { "GetGraniteGrinderSelected",       NERPFunc__GetGraniteGrinderSelected,       NERPS_ARGS_0 },
	/*121*/ { "GetChromeCrusherSelected",        NERPFunc__GetChromeCrusherSelected,        NERPS_ARGS_0 },
	/*122*/ { "GetTutorialBlockIsPath",          NERPFunc__GetTutorialBlockIsPath,          NERPS_ARGS_1 },
	/*123*/ { "GetGunstationIconClicked",        NERPFunc__GetGunstationIconClicked,        NERPS_ARGS_0 },
	/*124*/ { "SetGunstationIconClicked",        NERPFunc__SetGunstationIconClicked,        NERPS_ARGS_1_NORETURN },
	/*125*/ { "FlashGunstationIcon",             NERPFunc__FlashGunstationIcon,             NERPS_ARGS_1_NORETURN },
	/*126*/ { "GetGunstationsBuilt",             NERPFunc__GetGunstationsBuilt,             NERPS_ARGS_0 },
	/*127*/ { "SetOreAtIconPositions",           NERPFunc__SetOreAtIconPositions,           NERPS_ARGS_2_NORETURN },
	/*128*/ { "GetVehicleTeleportsBuilt",        NERPFunc__GetVehicleTeleportsBuilt,        NERPS_ARGS_0 },
	/*129*/ { "GetVehicleTransportIconClicked",  NERPFunc__GetVehicleTransportIconClicked,  NERPS_ARGS_0 },
	/*130*/ { "SetVehicleTransportIconClicked",  NERPFunc__SetVehicleTransportIconClicked,  NERPS_ARGS_1_NORETURN },
	/*131*/ { "FlashVehicleTransportIcon",       NERPFunc__FlashVehicleTransportIcon,       NERPS_ARGS_1_NORETURN },
	/*132*/ { "GetUpgradeStationIconClicked",    NERPFunc__GetUpgradeStationIconClicked,    NERPS_ARGS_0 },
	/*133*/ { "SetUpgradeStationIconClicked",    NERPFunc__SetUpgradeStationIconClicked,    NERPS_ARGS_1_NORETURN },
	/*134*/ { "FlashUpgradeStationIcon",         NERPFunc__FlashUpgradeStationIcon,         NERPS_ARGS_1_NORETURN },
	/*135*/ { "GetUpgradeStationsBuilt",         NERPFunc__GetUpgradeStationsBuilt,         NERPS_ARGS_0 },
	/*136*/ { "SetTutorialBlockIsGround",        NERPFunc__SetTutorialBlockIsGround,        NERPS_ARGS_2_NORETURN },
	/*137*/ { "SetTutorialBlockIsPath",          NERPFunc__SetTutorialBlockIsPath,          NERPS_ARGS_2_NORETURN },
	/*138*/ { "CameraLockOnObject",              NERPFunc__CameraLockOnObject,              NERPS_ARGS_1_NORETURN },
	/*139*/ { "CameraUnlock",                    NERPFunc__CameraUnlock,                    NERPS_ARGS_0_NORETURN },
	/*140*/ { "CameraZoomIn",                    NERPFunc__CameraZoomIn,                    NERPS_ARGS_1_NORETURN },
	/*141*/ { "CameraZoomOut",                   NERPFunc__CameraZoomOut,                   NERPS_ARGS_1_NORETURN },
	/*142*/ { "CameraRotate",                    NERPFunc__CameraRotate,                    NERPS_ARGS_1_NORETURN },
	/*143*/ { "GetCameraAtTutorial",             NERPFunc__GetCameraAtTutorial,             NERPS_ARGS_1 },
	/*144*/ { "GetSelectedRecordObject",         NERPFunc__GetSelectedRecordObject,         NERPS_ARGS_0 },
	/*145*/ { "GetSmallHelicopterSelected",      NERPFunc__GetSmallHelicopterSelected,      NERPS_ARGS_0 },
	/*146*/ { "GetRapidRiderSelected",           NERPFunc__GetRapidRiderSelected,           NERPS_ARGS_0 },
	/*147*/ { "GetMiniFigureinRapidRider",       NERPFunc__GetMiniFigureinRapidRider,       NERPS_ARGS_0 },
	/*148*/ { "GetDismountIconClicked",          NERPFunc__GetDismountIconClicked,          NERPS_ARGS_0 },
	/*149*/ { "SetDismountIconClicked",          NERPFunc__SetDismountIconClicked,          NERPS_ARGS_1_NORETURN },
	/*150*/ { "FlashDismountIcon",               NERPFunc__FlashDismountIcon,               NERPS_ARGS_1_NORETURN },
	/*151*/ { "GetGetToolIconClicked",           NERPFunc__GetGetToolIconClicked,           NERPS_ARGS_0 },
	/*152*/ { "SetGetToolIconClicked",           NERPFunc__SetGetToolIconClicked,           NERPS_ARGS_1_NORETURN },
	/*153*/ { "FlashGetToolIcon",                NERPFunc__FlashGetToolIcon,                NERPS_ARGS_1_NORETURN },
	/*154*/ { "GetAnyKeyPressed",                NERPFunc__GetAnyKeyPressed,                NERPS_ARGS_0 },
	/*155*/ { "SetPauseGame",                    NERPFunc__SetPauseGame,                    NERPS_ARGS_1_NORETURN },
	/*156*/ { "GetGetLaserIconClicked",          NERPFunc__GetGetLaserIconClicked,          NERPS_ARGS_0 },
	/*157*/ { "SetGetLaserIconClicked",          NERPFunc__SetGetLaserIconClicked,          NERPS_ARGS_1_NORETURN },
	/*158*/ { "FlashGetLaserIcon",               NERPFunc__FlashGetLaserIcon,               NERPS_ARGS_1_NORETURN },
	/*159*/ { "SetRockMonsterAtTutorial",        NERPFunc__SetRockMonsterAtTutorial,        NERPS_ARGS_1_NORETURN },
	/*160*/ { "GetCallToArmsButtonClicked",      NERPFunc__GetCallToArmsButtonClicked,      NERPS_ARGS_0 },
	/*161*/ { "GetRockMonstersDestroyed",        NERPFunc__GetRockMonstersDestroyed,        NERPS_ARGS_0 },
	/*162*/ { "SetGetPusherIconClicked",         NERPFunc__SetGetPusherIconClicked,         NERPS_ARGS_1_NORETURN },
	/*163*/ { "GetGetPusherIconClicked",         NERPFunc__GetGetPusherIconClicked,         NERPS_ARGS_0 },
	/*164*/ { "FlashGetPusherIcon",              NERPFunc__FlashGetPusherIcon,              NERPS_ARGS_1_NORETURN },
	/*165*/ { "GetRockMonsterRunningAway",       NERPFunc__GetRockMonsterRunningAway,       NERPS_ARGS_0 },
	/*166*/ { "SetCallToArms",                   NERPFunc__SetCallToArms,                   NERPS_ARGS_1_NORETURN },
	/*167*/ { "FlashPowerStationIcon",           NERPFunc__FlashPowerStationIcon,           NERPS_ARGS_1_NORETURN },
	/*168*/ { "SetPowerstationIconClicked",      NERPFunc__SetPowerstationIconClicked,      NERPS_ARGS_1_NORETURN },
	/*169*/ { "GetPowerstationIconClicked",      NERPFunc__GetPowerstationIconClicked,      NERPS_ARGS_0 },
	/*170*/ { "GetPowerstationsBuilt",           NERPFunc__GetPowerstationsBuilt,           NERPS_ARGS_0 },
	/*171*/ { "SetAttackDefer",                  NERPFunc__SetAttackDefer,                  NERPS_ARGS_1_NORETURN },
	/*172*/ { "SetRockMonsterPainThreshold",     NERPFunc__SetRockMonsterPainThreshold,     NERPS_ARGS_1_NORETURN },
	/*173*/ { "SetRockMonsterHealth",            NERPFunc__SetRockMonsterHealth,            NERPS_ARGS_1_NORETURN },
	/*174*/ { "SetGameSpeed",                    NERPFunc__SetGameSpeed,                    NERPS_ARGS_2_NORETURN },
	/*175*/ { "FlashBarracksIcon",               NERPFunc__FlashBarracksIcon,               NERPS_ARGS_1_NORETURN },
	/*176*/ { "SetBarracksIconClicked",          NERPFunc__SetBarracksIconClicked,          NERPS_ARGS_1_NORETURN },
	/*177*/ { "GetBarracksIconClicked",          NERPFunc__GetBarracksIconClicked,          NERPS_ARGS_0 },
	/*178*/ { "GetRecordObjectAtTutorial",       NERPFunc__GetRecordObjectAtTutorial,       NERPS_ARGS_1 },
	/*179*/ { "GetHiddenObjectsFound",           NERPFunc__GetHiddenObjectsFound,           NERPS_ARGS_0 },
	/*180*/ { "SetHiddenObjectsFound",           NERPFunc__SetHiddenObjectsFound,           NERPS_ARGS_1_NORETURN },
	/*181*/ { "GetOxygenLevel",                  NERPFunc__GetOxygenLevel,                  NERPS_ARGS_0 },
	/*182*/ { "FlashGeodomeIcon",                NERPFunc__FlashGeodomeIcon,                NERPS_ARGS_1_NORETURN },
	/*183*/ { "GetGeodomeIconClicked",           NERPFunc__GetGeodomeIconClicked,           NERPS_ARGS_0 },
	/*184*/ { "SetGeodomeIconClicked",           NERPFunc__SetGeodomeIconClicked,           NERPS_ARGS_1_NORETURN },
	/*185*/ { "GetGeodomeBuilt",                 NERPFunc__GetGeodomeBuilt,                 NERPS_ARGS_0 },
	/*186*/ { "AddStoredOre",                    NERPFunc__AddStoredOre,                    NERPS_ARGS_1_NORETURN },
	/*187*/ { "GenerateSlug",                    NERPFunc__GenerateSlug,                    NERPS_ARGS_0_NORETURN },
	/*188*/ { "GetSlugsOnLevel",                 NERPFunc__GetSlugsOnLevel,                 NERPS_ARGS_0 },
	/*189*/ { "GetMonstersOnLevel",              NERPFunc__GetMonstersOnLevel,              NERPS_ARGS_0 },
	/*190*/ { "SetCongregationAtTutorial",       NERPFunc__SetCongregationAtTutorial,       NERPS_ARGS_2_NORETURN },
	/*191*/ { "SetObjectiveSwitch",              NERPFunc__SetObjectiveSwitch,              NERPS_ARGS_1_NORETURN },
	/*192*/ { "GetObjectiveSwitch",              NERPFunc__GetObjectiveSwitch,              NERPS_ARGS_0 },
	/*193*/ { "GetGraniteGrindersOnLevel",       NERPFunc__GetGraniteGrindersOnLevel,       NERPS_ARGS_0 },
	/*194*/ { "GetSmallDiggersOnLevel",          NERPFunc__GetSmallDiggersOnLevel,          NERPS_ARGS_0 },
	/*195*/ { "GetDocksBuilt",                   NERPFunc__GetDocksBuilt,                   NERPS_ARGS_0 },
	/*196*/ { "GetRapidRidersOnLevel",           NERPFunc__GetRapidRidersOnLevel,           NERPS_ARGS_0 },
	/*197*/ { "GetUnitAtBlock",                  NERPFunc__GetUnitAtBlock,                  NERPS_ARGS_1 },
	/*198*/ { "GetSmallHelicoptersOnLevel",      NERPFunc__GetSmallHelicoptersOnLevel,      NERPS_ARGS_0 },
	/*199*/ { "GetRecordObjectAmountAtTutorial", NERPFunc__GetRecordObjectAmountAtTutorial, NERPS_ARGS_1 },
	/*200*/ { "AdvanceMessage",                  NERPFunc__AdvanceMessage,                  NERPS_ARGS_0_NORETURN },
	/*201*/ { "AllowCameraMovement",             NERPFunc__AllowCameraMovement,             NERPS_ARGS_1_NORETURN },
	/*202*/ { "ClickOnlyObjects",                NERPFunc__ClickOnlyObjects,                NERPS_ARGS_0_NORETURN },
	/*203*/ { "ClickOnlyMap",                    NERPFunc__ClickOnlyMap,                    NERPS_ARGS_0_NORETURN },
	/*204*/ { "ClickOnlyIcon",                   NERPFunc__ClickOnlyIcon,                   NERPS_ARGS_0_NORETURN },
	/*205*/ { "DisallowAll",                     NERPFunc__DisallowAll,                     NERPS_ARGS_0_NORETURN },
	/*206*/ { "SupressArrow",                    NERPFunc__SupressArrow,                    NERPS_ARGS_1_NORETURN },
	/*207*/ { "GetMiniFigureinGraniteGrinder",   NERPFunc__GetMiniFigureinGraniteGrinder,   NERPS_ARGS_0 },
	/*208*/ { "GetMiniFigureinChromeCrusher",    NERPFunc__GetMiniFigureinChromeCrusher,    NERPS_ARGS_0 },
	/*209*/ { "GetMessagesAreUpToDate",          NERPFunc__GetMessagesAreUpToDate,          NERPS_ARGS_0 },
	/*210*/ { "SetCrystalPriority",              NERPFunc__SetCrystalPriority,              NERPS_ARGS_1_NORETURN },
	/*211*/ { "MakeSomeoneOnThisBlockPickUpSomethingOnThisBlock", NERPFunc__MakeSomeoneOnThisBlockPickUpSomethingOnThisBlock, NERPS_ARGS_1_NORETURN }, // why is this name so obnoxiously long???
	/*212*/ { "SetTrainIconClicked",             NERPFunc__SetTrainIconClicked,             NERPS_ARGS_1_NORETURN },
	/*213*/ { "GetTrainIconClicked",             NERPFunc__GetTrainIconClicked,             NERPS_ARGS_0 },
	/*214*/ { "FlashTrainIcon",                  NERPFunc__FlashTrainIcon,                  NERPS_ARGS_1_NORETURN },
	/*215*/ { "SetTrainDriverIconClicked",       NERPFunc__SetTrainDriverIconClicked,       NERPS_ARGS_1_NORETURN },
	/*216*/ { "GetTrainDriverIconClicked",       NERPFunc__GetTrainDriverIconClicked,       NERPS_ARGS_0 },
	/*217*/ { "FlashTrainDriverIcon",            NERPFunc__FlashTrainDriverIcon,            NERPS_ARGS_1_NORETURN },
	/*218*/ { "SetTrainPilotIconClicked",        NERPFunc__SetTrainPilotIconClicked,        NERPS_ARGS_1_NORETURN },
	/*219*/ { "GetTrainPilotIconClicked",        NERPFunc__GetTrainPilotIconClicked,        NERPS_ARGS_0 },
	/*220*/ { "FlashTrainPilotIcon",             NERPFunc__FlashTrainPilotIcon,             NERPS_ARGS_1_NORETURN },
	/*221*/ { "SetTrainSailorIconClicked",       NERPFunc__SetTrainSailorIconClicked,       NERPS_ARGS_1_NORETURN },
	/*222*/ { "GetTrainSailorIconClicked",       NERPFunc__GetTrainSailorIconClicked,       NERPS_ARGS_0 },
	/*223*/ { "FlashTrainSailorIcon",            NERPFunc__FlashTrainSailorIcon,            NERPS_ARGS_1_NORETURN },
	/*224*/ { "GetSmallTruckSelected",           NERPFunc__GetSmallTruckSelected,           NERPS_ARGS_0 },
	/*225*/ { "GetMiniFigureinSmallTruck",       NERPFunc__GetMiniFigureinSmallTruck,       NERPS_ARGS_0 },
	/*226*/ { "GetMiniFigureinSmallHelicopter",  NERPFunc__GetMiniFigureinSmallHelicopter,  NERPS_ARGS_0 },
	/*227*/ { "SetBarracksLevel",                NERPFunc__SetBarracksLevel,                NERPS_ARGS_1_NORETURN },
	/*228*/ { "SetDocksLevel",                   NERPFunc__SetDocksLevel,                   NERPS_ARGS_1_NORETURN },
	/*229*/ { "SetGeoDomeLevel",                 NERPFunc__SetGeoDomeLevel,                 NERPS_ARGS_1_NORETURN },
	/*230*/ { "SetPowerstationLevel",            NERPFunc__SetPowerstationLevel,            NERPS_ARGS_1_NORETURN },
	/*231*/ { "SetToolStoreLevel",               NERPFunc__SetToolStoreLevel,               NERPS_ARGS_1_NORETURN },
	/*232*/ { "SetGunstationLevel",              NERPFunc__SetGunstationLevel,              NERPS_ARGS_1_NORETURN },
	/*233*/ { "SetTeleportPadLevel",             NERPFunc__SetTeleportPadLevel,             NERPS_ARGS_1_NORETURN },
	/*234*/ { "SetSuperTeleportLevel",           NERPFunc__SetSuperTeleportLevel,           NERPS_ARGS_1_NORETURN },
	/*235*/ { "SetUpgradeStationLevel",          NERPFunc__SetUpgradeStationLevel,          NERPS_ARGS_1_NORETURN },
	/*236*/ { "GetBarracksSelected",             NERPFunc__GetBarracksSelected,             NERPS_ARGS_0 },
	/*237*/ { "GetDocksSelected",                NERPFunc__GetDocksSelected,                NERPS_ARGS_0 },
	/*238*/ { "GetGeoDomeSelected",              NERPFunc__GetGeoDomeSelected,              NERPS_ARGS_0 },
	/*239*/ { "GetPowerstationSelected",         NERPFunc__GetPowerstationSelected,         NERPS_ARGS_0 },
	/*240*/ { "GetToolStoreSelected",            NERPFunc__GetToolStoreSelected,            NERPS_ARGS_0 },
	/*241*/ { "GetGunstationSelected",           NERPFunc__GetGunstationSelected,           NERPS_ARGS_0 },
	/*242*/ { "GetTeleportPadSelected",          NERPFunc__GetTeleportPadSelected,          NERPS_ARGS_0 },
	/*243*/ { "GetSuperTeleportSelected",        NERPFunc__GetSuperTeleportSelected,        NERPS_ARGS_0 },
	/*244*/ { "GetUpgradeStationSelected",       NERPFunc__GetUpgradeStationSelected,       NERPS_ARGS_0 },
	/*245*/ { "SetUpgradeBuildingIconClicked",   NERPFunc__SetUpgradeBuildingIconClicked,   NERPS_ARGS_1_NORETURN },
	/*246*/ { "GetUpgradeBuildingIconClicked",   NERPFunc__GetUpgradeBuildingIconClicked,   NERPS_ARGS_0 },
	/*247*/ { "FlashUpgradeBuildingIcon",        NERPFunc__FlashUpgradeBuildingIcon,        NERPS_ARGS_1_NORETURN },
	/*248*/ { "GetBuildingsTeleported",          NERPFunc__GetBuildingsTeleported,          NERPS_ARGS_0 },
	/*249*/ { "SetBuildingsTeleported",          NERPFunc__SetBuildingsTeleported,          NERPS_ARGS_1_NORETURN },
	/*250*/ { "CameraLockOnMonster",             NERPFunc__CameraLockOnMonster,             NERPS_ARGS_1_NORETURN },
	/*251*/ { "SetMonsterAttackPowerstation",    NERPFunc__SetMonsterAttackPowerstation,    NERPS_ARGS_1_NORETURN },
	/*252*/ { "ClickOnlyCalltoarms",             NERPFunc__ClickOnlyCalltoarms,             NERPS_ARGS_0_NORETURN },
	/*253*/ { "FlashCallToArmsIcon",             NERPFunc__FlashCallToArmsIcon,             NERPS_ARGS_1_NORETURN },
	/*254*/ { "SetRecordObjectPointer",          NERPFunc__SetRecordObjectPointer,          NERPS_ARGS_1_NORETURN },
	/*255*/ { "GetGetSonicBlasterIconClicked",   NERPFunc__GetGetSonicBlasterIconClicked,   NERPS_ARGS_0 },
	/*256*/ { "SetGetSonicBlasterIconClicked",   NERPFunc__SetGetSonicBlasterIconClicked,   NERPS_ARGS_1_NORETURN },
	/*257*/ { "FlashGetSonicBlasterIcon",        NERPFunc__FlashGetSonicBlasterIcon,        NERPS_ARGS_1_NORETURN },
	/*258*/ { "GetDropSonicBlasterIconClicked",  NERPFunc__GetDropSonicBlasterIconClicked,  NERPS_ARGS_0 },
	/*259*/ { "SetDropSonicBlasterIconClicked",  NERPFunc__SetDropSonicBlasterIconClicked,  NERPS_ARGS_1_NORETURN },
	/*260*/ { "FlashDropSonicBlasterIcon",       NERPFunc__FlashDropSonicBlasterIcon,       NERPS_ARGS_1_NORETURN },
	/*261*/ { "GetMonsterAtTutorial",            NERPFunc__GetMonsterAtTutorial,            NERPS_ARGS_1 },
	/*262*/ { "SetMonsterAttackNowt",            NERPFunc__SetMonsterAttackNowt,            NERPS_ARGS_1_NORETURN },
	/*263*/ { "GetPlaceFenceIconClicked",        NERPFunc__GetPlaceFenceIconClicked,        NERPS_ARGS_0 },
	/*264*/ { "SetPlaceFenceIconClicked",        NERPFunc__SetPlaceFenceIconClicked,        NERPS_ARGS_1_NORETURN },
	/*265*/ { "FlashPlaceFenceIcon",             NERPFunc__FlashPlaceFenceIcon,             NERPS_ARGS_1_NORETURN },
	/*266*/ { "GetLevel1BarracksBuilt",          NERPFunc__GetLevel1BarracksBuilt,          NERPS_ARGS_0 },
	/*267*/ { "GetLevel1DocksBuilt",             NERPFunc__GetLevel1DocksBuilt,             NERPS_ARGS_0 },
	/*268*/ { "GetLevel1GeodomeBuilt",           NERPFunc__GetLevel1GeodomeBuilt,           NERPS_ARGS_0 },
	/*269*/ { "GetLevel1PowerstationsBuilt",     NERPFunc__GetLevel1PowerstationsBuilt,     NERPS_ARGS_0 },
	/*270*/ { "GetLevel1ToolStoresBuilt",        NERPFunc__GetLevel1ToolStoresBuilt,        NERPS_ARGS_0 },
	/*271*/ { "GetLevel1GunstationsBuilt",       NERPFunc__GetLevel1GunstationsBuilt,       NERPS_ARGS_0 },
	/*272*/ { "GetLevel1TeleportsBuilt",         NERPFunc__GetLevel1TeleportsBuilt,         NERPS_ARGS_0 },
	/*273*/ { "GetLevel1VehicleTeleportsBuilt",  NERPFunc__GetLevel1VehicleTeleportsBuilt,  NERPS_ARGS_0 },
	/*274*/ { "GetLevel1UpgradeStationsBuilt",   NERPFunc__GetLevel1UpgradeStationsBuilt,   NERPS_ARGS_0 },
	/*275*/ { "GetLevel2BarracksBuilt",          NERPFunc__GetLevel2BarracksBuilt,          NERPS_ARGS_0 },
	/*276*/ { "GetLevel2DocksBuilt",             NERPFunc__GetLevel2DocksBuilt,             NERPS_ARGS_0 },
	/*277*/ { "GetLevel2GeodomeBuilt",           NERPFunc__GetLevel2GeodomeBuilt,           NERPS_ARGS_0 },
	/*278*/ { "GetLevel2PowerstationsBuilt",     NERPFunc__GetLevel2PowerstationsBuilt,     NERPS_ARGS_0 },
	/*279*/ { "GetLevel2ToolStoresBuilt",        NERPFunc__GetLevel2ToolStoresBuilt,        NERPS_ARGS_0 },
	/*280*/ { "GetLevel2GunstationsBuilt",       NERPFunc__GetLevel2GunstationsBuilt,       NERPS_ARGS_0 },
	/*281*/ { "GetLevel2TeleportsBuilt",         NERPFunc__GetLevel2TeleportsBuilt,         NERPS_ARGS_0 },
	/*282*/ { "GetLevel2VehicleTeleportsBuilt",  NERPFunc__GetLevel2VehicleTeleportsBuilt,  NERPS_ARGS_0 },
	/*283*/ { "GetLevel2UpgradeStationsBuilt",   NERPFunc__GetLevel2UpgradeStationsBuilt,   NERPS_ARGS_0 },
	/*284*/ { "GetPoweredBarracksBuilt",         NERPFunc__GetPoweredBarracksBuilt,         NERPS_ARGS_0 },
	/*285*/ { "GetPoweredDocksBuilt",            NERPFunc__GetPoweredDocksBuilt,            NERPS_ARGS_0 },
	/*286*/ { "GetPoweredGeodomeBuilt",          NERPFunc__GetPoweredGeodomeBuilt,          NERPS_ARGS_0 },
	/*287*/ { "GetPoweredPowerstationsBuilt",    NERPFunc__GetPoweredPowerstationsBuilt,    NERPS_ARGS_0 },
	/*288*/ { "GetPoweredToolStoresBuilt",       NERPFunc__GetPoweredToolStoresBuilt,       NERPS_ARGS_0 },
	/*289*/ { "GetPoweredGunstationsBuilt",      NERPFunc__GetPoweredGunstationsBuilt,      NERPS_ARGS_0 },
	/*290*/ { "GetPoweredTeleportsBuilt",        NERPFunc__GetPoweredTeleportsBuilt,        NERPS_ARGS_0 },
	/*291*/ { "GetPoweredVehicleTeleportsBuilt", NERPFunc__GetPoweredVehicleTeleportsBuilt, NERPS_ARGS_0 },
	/*292*/ { "GetPoweredUpgradeStationsBuilt",  NERPFunc__GetPoweredUpgradeStationsBuilt,  NERPS_ARGS_0 },
	/*293*/ { "**End Of List**",                 NERPFunc__False,                           NERPS_END_OF_LIST } // (REAL dummy function, NERPS_END_OF_LIST (7) is an invalid value)
};

